name: Feature Request
description: You want to submit a feature request? Open this one.
title: "[FEATURE]: <title>"
labels:
  - kind/feature
body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other relevant information about the feature request.
