name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-jspolicy:
    runs-on: ubuntu-latest
    needs:
      - compile
    defaults:
      run:
        working-directory: ./jspolicy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./jspolicy/package.json
      - run: npm install --include=dev
      - run: npm test
      - uses: actions/upload-artifact@v4
        with:
          name: test-jspolicy
          path: 'jspolicy/coverage'
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs:
      - test-jspolicy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: 'test-*'
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  compile-jspolicy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jspolicy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./jspolicy/package.json
      - run: npm install --include=dev
      - run: npm run compile
      - uses: actions/upload-artifact@v4
        with:
          name: policies-jspolicy
          path: 'jspolicy/policies/*'
          retention-days: 7

  e2e:
    runs-on: ubuntu-latest
    needs:
      - compile-jspolicy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          pattern: 'policies-*'
      - run: |
          tree
      - run: |
          make \
            cluster
      - run: |
          kubectl apply -f policies-jspolicy
      - run: |
          make \
            test-e2e
